sudo: true
language: python
python:
  - '2.7'
  - '3.4'
env:
  global:
    - DB=postgres
  matrix:
    - DJANGO=">=1.7,<1.8"
    - DJANGO=">=1.8,<1.9"
    - DJANGO=">=1.9,<1.10"
before_install:
  - sudo /etc/init.d/postgresql stop
  - sudo apt-get -y remove --purge postgresql-9.1
  - sudo apt-get -y remove --purge postgresql-9.2
  - sudo apt-get -y remove --purge postgresql-9.3
  - sudo apt-get -y remove --purge postgresql-9.4
  - sudo apt-get -y autoremove
  - sudo apt-key adv --keyserver keys.gnupg.net --recv-keys 7FCC7D46ACCC4CF8
  - sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main 9.5" >> /etc/apt/sources.list.d/postgresql.list'
  - sudo apt-get update
  - sudo apt-get -y install postgresql-9.5
  - sudo sh -c 'echo "local all postgres trust" > /etc/postgresql/9.5/main/pg_hba.conf'
  - sudo sh -c 'echo -n "host all all 127.0.0.1/32 trust" >> /etc/postgresql/9.5/main/pg_hba.conf'
  - sudo /etc/init.d/postgresql restart
  - psql --version
install:
  - pip install -q coverage flake8 Django$DJANGO django-nose>=1.4
  - pip install -r requirements/docs.txt
before_script:
  - psql -c 'CREATE DATABASE manager_utils;' -U postgres
script:
  - flake8 .
  - coverage run setup.py test
  - coverage report --fail-under=100
  - python setup.py install
  - python setup.py build_sphinx
