language: python
python:
  - '2.7'
env:
  - DJANGO=1.5 DB=postgres
  - DJANGO=1.6.1 DB=postgres
install:
  - pip install -q Django==$DJANGO
  - pip install -r requirements.txt
before_script:
  - find . | grep .py$ | grep -v /migrations | xargs pep8 --max-line-length=120
  - find . | grep .py$ | grep -v /migrations | grep -v __init__.py | xargs pyflakes
  - psql -c 'CREATE DATABASE manager_utils;' -U postgres
script:
  - coverage run --source='manager_utils' --branch manage.py test
  - coverage report --fail-under=100
